import { useState } from 'react';
import { ReviewerCard, ReviewerCardEmpty } from './ReviewerCard';
import type {
  TopicSelectionResearchSliceOptionSetRecord,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-v1b-research-slice-contracts';

type SliceOptionSetCardProps = {
  sliceOptionSets: TopicSelectionResearchSliceOptionSetRecord[];
};

function statusTone(status: string): 'neutral' | 'info' | 'success' | 'warning' | 'danger' {
  if (status === 'selected' || status === 'closed') return 'success';
  if (status === 'pending_human_review') return 'warning';
  return 'info';
}

/**
 * v1b ResearchSliceOptionSet surface — Phase 3.1 read-only view.
 *
 * Lists option sets generated by `PlanResearchSlice` runs, with metadata
 * about which option is recommended/selected and whether human review is
 * required. Write actions are owned by the harness-native v1b path.
 */
export function SliceOptionSetCard({ sliceOptionSets }: SliceOptionSetCardProps) {
  const [selectedId, setSelectedId] = useState<string | null>(
    sliceOptionSets[0]?.research_slice_option_set_id ?? null,
  );
  const active = sliceOptionSets.find((item) => item.research_slice_option_set_id === selectedId)
    ?? sliceOptionSets[0]
    ?? null;

  if (!active) {
    return (
      <article data-ui="card">
        <div data-ui="stack" data-direction="col" data-gap="2">
          <p data-ui="text" data-variant="label" data-tone="primary">ResearchSliceOptionSet</p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            该题目卡的 v1b 还没生成 ResearchSliceOptionSet。先确保 v1a 出口 ValidatedNeed + V1bInputBundle 已发布。
          </p>
        </div>
      </article>
    );
  }

  const optionSelector = sliceOptionSets.length > 1 ? (
    <select
      data-ui="select"
      data-size="sm"
      value={active.research_slice_option_set_id}
      onChange={(event) => setSelectedId(event.target.value)}
    >
      {sliceOptionSets.map((item) => (
        <option key={item.research_slice_option_set_id} value={item.research_slice_option_set_id}>
          {item.research_slice_option_set_id} · {item.status}
        </option>
      ))}
    </select>
  ) : null;

  return (
    <ReviewerCard
      kind="ResearchSliceOptionSet"
      subjectId={active.research_slice_option_set_id}
      status={{ label: active.status, tone: statusTone(active.status) }}
      chips={[
        { label: `options ${active.option_count}`, tone: 'info' },
        { label: `high-risk ${active.high_risk_option_count}`, tone: active.high_risk_option_count > 0 ? 'warning' : 'neutral' },
        ...(active.requires_human_review ? [{ label: 'human review', tone: 'warning' as const }] : []),
        ...(sliceOptionSets.length > 1 ? [{ label: `history ${sliceOptionSets.length}`, tone: 'neutral' as const }] : []),
      ]}
      verdict={
        <div data-ui="stack" data-direction="col" data-gap="1">
          <p data-ui="text" data-variant="body" data-tone="primary">
            comparison：{active.comparison_summary || '— 无 comparison_summary —'}
          </p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            recommended={active.recommended_option_id ?? '—'} · selected={active.selected_option_id ?? '—'}
          </p>
          {optionSelector ? (
            <div data-ui="stack" data-direction="row" data-gap="2" data-align="center">
              <span data-ui="text" data-variant="caption" data-tone="muted">切换 option set</span>
              {optionSelector}
            </div>
          ) : null}
        </div>
      }
      support={
        active.comparison_axes.length === 0 ? (
          <ReviewerCardEmpty label="没有声明的 comparison_axes。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            <p data-ui="text" data-variant="caption" data-tone="primary">
              comparison_axes（{active.comparison_axes.length}）
            </p>
            <ul data-ui="stack" data-direction="col" data-gap="0">
              {active.comparison_axes.slice(0, 6).map((axis, idx) => (
                <li key={`${axis}-${idx}`}>
                  <p data-ui="text" data-variant="caption" data-tone="muted">· {axis}</p>
                </li>
              ))}
            </ul>
          </div>
        )
      }
      challenge={
        active.unresolved_disagreements.length === 0 && active.missing_option_types.length === 0 ? (
          <ReviewerCardEmpty label="无未解 disagreement / missing option type。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            {active.unresolved_disagreements.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                unresolved_disagreements：{active.unresolved_disagreements.length}
              </p>
            ) : null}
            {active.missing_option_types.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                missing_option_types：{active.missing_option_types.join(' · ')}
              </p>
            ) : null}
          </div>
        )
      }
      blockers={
        active.human_review_triggers.length === 0 ? (
          <ReviewerCardEmpty label="无 human_review_triggers。" />
        ) : (
          <div data-ui="stack" data-direction="row" data-gap="1" data-wrap="wrap">
            {active.human_review_triggers.map((trigger) => (
              <span key={trigger} data-ui="badge" data-variant="subtle" data-tone="warning">{trigger}</span>
            ))}
          </div>
        )
      }
      nextActions={
        <div data-ui="stack" data-direction="col" data-gap="2">
          {active.selected_option_id ? (
            <p data-ui="text" data-variant="caption" data-tone="primary">
              → 已选定 option：{active.selected_option_id}
            </p>
          ) : (
            <ReviewerCardEmpty label="等待 v1b WorkflowHarness N5 选定 ResearchSlice。" />
          )}
        </div>
      }
      footer={`created_at=${active.created_at} · updated_at=${active.updated_at}`}
    />
  );
}
