import { useCallback, useEffect, useState } from 'react';
import { ReviewerCard, ReviewerCardEmpty } from './ReviewerCard';
import type {
  TopicSelectionResearchSliceOptionRecord,
  TopicSelectionResearchSliceOptionSetRecord,
  TopicSelectionSliceSelectionDecision,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-v1b-research-slice-contracts';
import {
  listResearchSliceOptionsByOptionSet,
  submitSliceSelectionDecision,
} from '../api/v1b';

type SliceOptionSetCardProps = {
  sliceOptionSets: TopicSelectionResearchSliceOptionSetRecord[];
  onMutated?: () => void;
};

function statusTone(status: string): 'neutral' | 'info' | 'success' | 'warning' | 'danger' {
  if (status === 'selected' || status === 'closed') return 'success';
  if (status === 'pending_human_review') return 'warning';
  return 'info';
}

/**
 * v1b ResearchSliceOptionSet surface — Phase 3.1 read-only view.
 *
 * Lists option sets generated by `PlanResearchSlice` runs, with metadata
 * about which option is recommended/selected and whether human review is
 * required. Selection forms (SliceSelectionDecision human-confirm) land in
 * Phase 3.2 (interactive forms).
 */
export function SliceOptionSetCard({ sliceOptionSets, onMutated }: SliceOptionSetCardProps) {
  const [selectedId, setSelectedId] = useState<string | null>(
    sliceOptionSets[0]?.research_slice_option_set_id ?? null,
  );
  const active = sliceOptionSets.find((item) => item.research_slice_option_set_id === selectedId)
    ?? sliceOptionSets[0]
    ?? null;

  if (!active) {
    return (
      <article data-ui="card">
        <div data-ui="stack" data-direction="col" data-gap="2">
          <p data-ui="text" data-variant="label" data-tone="primary">ResearchSliceOptionSet</p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            该题目卡的 v1b 还没生成 ResearchSliceOptionSet。先确保 v1a 出口 ValidatedNeed + V1bInputBundle 已发布。
          </p>
        </div>
      </article>
    );
  }

  const optionSelector = sliceOptionSets.length > 1 ? (
    <select
      data-ui="select"
      data-size="sm"
      value={active.research_slice_option_set_id}
      onChange={(event) => setSelectedId(event.target.value)}
    >
      {sliceOptionSets.map((item) => (
        <option key={item.research_slice_option_set_id} value={item.research_slice_option_set_id}>
          {item.research_slice_option_set_id} · {item.status}
        </option>
      ))}
    </select>
  ) : null;

  return (
    <ReviewerCard
      kind="ResearchSliceOptionSet"
      subjectId={active.research_slice_option_set_id}
      status={{ label: active.status, tone: statusTone(active.status) }}
      chips={[
        { label: `options ${active.option_count}`, tone: 'info' },
        { label: `high-risk ${active.high_risk_option_count}`, tone: active.high_risk_option_count > 0 ? 'warning' : 'neutral' },
        ...(active.requires_human_review ? [{ label: 'human review', tone: 'warning' as const }] : []),
        ...(sliceOptionSets.length > 1 ? [{ label: `history ${sliceOptionSets.length}`, tone: 'neutral' as const }] : []),
      ]}
      verdict={
        <div data-ui="stack" data-direction="col" data-gap="1">
          <p data-ui="text" data-variant="body" data-tone="primary">
            comparison：{active.comparison_summary || '— 无 comparison_summary —'}
          </p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            recommended={active.recommended_option_id ?? '—'} · selected={active.selected_option_id ?? '—'}
          </p>
          {optionSelector ? (
            <div data-ui="stack" data-direction="row" data-gap="2" data-align="center">
              <span data-ui="text" data-variant="caption" data-tone="muted">切换 option set</span>
              {optionSelector}
            </div>
          ) : null}
        </div>
      }
      support={
        active.comparison_axes.length === 0 ? (
          <ReviewerCardEmpty label="没有声明的 comparison_axes。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            <p data-ui="text" data-variant="caption" data-tone="primary">
              comparison_axes（{active.comparison_axes.length}）
            </p>
            <ul data-ui="stack" data-direction="col" data-gap="0">
              {active.comparison_axes.slice(0, 6).map((axis, idx) => (
                <li key={`${axis}-${idx}`}>
                  <p data-ui="text" data-variant="caption" data-tone="muted">· {axis}</p>
                </li>
              ))}
            </ul>
          </div>
        )
      }
      challenge={
        active.unresolved_disagreements.length === 0 && active.missing_option_types.length === 0 ? (
          <ReviewerCardEmpty label="无未解 disagreement / missing option type。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            {active.unresolved_disagreements.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                unresolved_disagreements：{active.unresolved_disagreements.length}
              </p>
            ) : null}
            {active.missing_option_types.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                missing_option_types：{active.missing_option_types.join(' · ')}
              </p>
            ) : null}
          </div>
        )
      }
      blockers={
        active.human_review_triggers.length === 0 ? (
          <ReviewerCardEmpty label="无 human_review_triggers。" />
        ) : (
          <div data-ui="stack" data-direction="row" data-gap="1" data-wrap="wrap">
            {active.human_review_triggers.map((trigger) => (
              <span key={trigger} data-ui="badge" data-variant="subtle" data-tone="warning">{trigger}</span>
            ))}
          </div>
        )
      }
      nextActions={
        <div data-ui="stack" data-direction="col" data-gap="2">
          {active.selected_option_id ? (
            <p data-ui="text" data-variant="caption" data-tone="primary">
              → 已选定 option：{active.selected_option_id}
            </p>
          ) : null}
          <SliceSelectionForm optionSet={active} onSubmitted={onMutated} />
        </div>
      }
      footer={`created_at=${active.created_at} · updated_at=${active.updated_at}`}
    />
  );
}

const SLICE_DECISIONS: Array<{ value: TopicSelectionSliceSelectionDecision; label: string }> = [
  { value: 'select', label: 'select · 选定一个 option' },
  { value: 'request_more_options', label: 'request_more_options · 要求重新规划' },
  { value: 'park', label: 'park · 暂搁' },
  { value: 'reject', label: 'reject · 否决整个 option set' },
];

type SliceSelectionFormProps = {
  optionSet: TopicSelectionResearchSliceOptionSetRecord;
  onSubmitted?: () => void;
};

/**
 * Phase 3.2 inline form — submit a SliceSelectionDecision.
 *
 * `decision === 'select'` requires a `selected_option_id`; other paths
 * skip option picking. Rationale必填，对应 design-spec §4039 红线（每个
 * human-confirmed 决策都需要书面理由）。
 */
function SliceSelectionForm({ optionSet, onSubmitted }: SliceSelectionFormProps) {
  const [decision, setDecision] = useState<TopicSelectionSliceSelectionDecision>(
    optionSet.recommended_option_id ? 'select' : 'request_more_options',
  );
  const [selectedOptionId, setSelectedOptionId] = useState<string>(
    optionSet.recommended_option_id ?? '',
  );
  const [rationale, setRationale] = useState('');
  const [options, setOptions] = useState<TopicSelectionResearchSliceOptionRecord[]>([]);
  const [loadingOptions, setLoadingOptions] = useState(false);
  const [optionError, setOptionError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [submittedId, setSubmittedId] = useState<string | null>(null);

  useEffect(() => {
    setDecision(optionSet.recommended_option_id ? 'select' : 'request_more_options');
    setSelectedOptionId(optionSet.recommended_option_id ?? '');
    setRationale('');
    setSubmitError(null);
    setSubmittedId(null);
  }, [optionSet.research_slice_option_set_id, optionSet.recommended_option_id]);

  useEffect(() => {
    let mounted = true;
    setLoadingOptions(true);
    setOptionError(null);
    void listResearchSliceOptionsByOptionSet(optionSet.research_slice_option_set_id)
      .then((records) => {
        if (mounted) setOptions(records);
      })
      .catch((caught) => {
        if (mounted) setOptionError(caught instanceof Error ? caught.message : '加载 options 失败。');
      })
      .finally(() => {
        if (mounted) setLoadingOptions(false);
      });
    return () => {
      mounted = false;
    };
  }, [optionSet.research_slice_option_set_id]);

  const isTerminal = optionSet.status === 'selected'
    || optionSet.status === 'rejected'
    || optionSet.status === 'superseded'
    || optionSet.status === 'parked'
    || Boolean(optionSet.selected_option_id);
  const requiresOptionId = decision === 'select';
  const canSubmit = !submitting
    && !isTerminal
    && rationale.trim().length > 0
    && (!requiresOptionId || selectedOptionId.trim().length > 0);

  const handleSubmit = useCallback(async () => {
    if (!canSubmit) return;
    setSubmitting(true);
    setSubmitError(null);
    try {
      const result = await submitSliceSelectionDecision(optionSet.research_slice_option_set_id, {
        decision,
        selection_rationale: rationale.trim(),
        selected_option_id: requiresOptionId ? selectedOptionId.trim() : null,
        decided_by: 'human',
      });
      setSubmittedId(result.slice_selection_decision_id);
      onSubmitted?.();
    } catch (caught) {
      setSubmitError(caught instanceof Error ? caught.message : '提交 SliceSelectionDecision 失败。');
    } finally {
      setSubmitting(false);
    }
  }, [canSubmit, optionSet.research_slice_option_set_id, decision, rationale, requiresOptionId, selectedOptionId, onSubmitted]);

  return (
    <section data-ui="section" data-padding="sm">
      <div data-ui="stack" data-direction="col" data-gap="1">
        <p data-ui="text" data-variant="label" data-tone="muted">SliceSelectionDecision · human confirm</p>
        {isTerminal ? (
          <p data-ui="text" data-variant="caption" data-tone="muted">
            该 option set 已 {optionSet.status}；如需新一轮，需 agent 层重新触发 PlanResearchSlice。
          </p>
        ) : (
          <>
            <select
              data-ui="select"
              data-size="md"
              value={decision}
              onChange={(event) => setDecision(event.target.value as TopicSelectionSliceSelectionDecision)}
            >
              {SLICE_DECISIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>{opt.label}</option>
              ))}
            </select>
            {requiresOptionId ? (
              loadingOptions ? (
                <p data-ui="text" data-variant="caption" data-tone="muted">加载 options…</p>
              ) : optionError ? (
                <p data-ui="text" data-variant="caption" data-tone="danger">{optionError}</p>
              ) : options.length === 0 ? (
                <p data-ui="text" data-variant="caption" data-tone="muted">该 option set 没有可选 options。</p>
              ) : (
                <select
                  data-ui="select"
                  data-size="md"
                  value={selectedOptionId}
                  onChange={(event) => setSelectedOptionId(event.target.value)}
                >
                  <option value="">— 选择 option —</option>
                  {options.map((opt) => (
                    <option key={opt.research_slice_option_id} value={opt.research_slice_option_id}>
                      [{opt.option_key}] {opt.slice_statement.slice(0, 80) || opt.research_slice_option_id}
                    </option>
                  ))}
                </select>
              )
            ) : null}
            <textarea
              data-ui="textarea"
              data-size="md"
              rows={3}
              placeholder="selection_rationale（必填）"
              value={rationale}
              onChange={(event) => setRationale(event.target.value)}
            />
            <div data-ui="stack" data-direction="row" data-gap="1" data-wrap="wrap" data-align="center">
              {canSubmit ? (
                <button
                  type="button"
                  data-ui="button"
                  data-variant="primary"
                  data-size="sm"
                  disabled={submitting}
                  onClick={() => void handleSubmit()}
                >
                  {submitting ? '提交中…' : '提交 SliceSelectionDecision'}
                </button>
              ) : (
                <button
                  type="button"
                  data-ui="button"
                  data-variant="secondary"
                  data-size="sm"
                  disabled
                >
                  提交 SliceSelectionDecision
                </button>
              )}
              {submittedId ? (
                <span data-ui="badge" data-variant="subtle" data-tone="success">已创建：{submittedId}</span>
              ) : null}
            </div>
            {submitError ? (
              <p data-ui="text" data-variant="caption" data-tone="danger">{submitError}</p>
            ) : null}
          </>
        )}
      </div>
    </section>
  );
}
